Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
src += Glob('*.cxx')
src += Glob('air302/*.cxx')

CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('Devices', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
